Call initial_script if we're a headnode.

diff --git a/usr/src/lib/brand/joyent/zone/svc-joyinit b/usr/src/lib/brand/joyent/zone/svc-joyinit
--- a/usr/src/lib/brand/joyent/zone/svc-joyinit
+++ b/usr/src/lib/brand/joyent/zone/svc-joyinit
@@ -24,6 +24,7 @@
 # Use is subject to license terms.
 
 . /lib/svc/share/smf_include.sh
+. /lib/svc/share/joyent_include.sh
 
 # Make sure working directory is / to prevent unmounting problems.
 cd /
@@ -31,6 +32,8 @@ PATH=/usr/sbin:/usr/bin; export PATH
 
 case "$1" in
 'start')
+
+    enable_ur="true"
 
     # Grab AMQP vars from kernel cmdline
     /usr/bin/bootparams | grep "^rabbitmq=" | cut -d'=' -f2 \
@@ -41,15 +44,42 @@ case "$1" in
         export AMQP_PASSWORD="${pass}"
     }
 
+    # If we're a headnode, we'll not have AMQP args on the cmdline, and we want
+    # to run an initial_script first anyway.
+    if [[ `/bin/bootparams | grep "headnode=true" > /dev/null 2>&1` ]]; then
+        . /lib/svc/share/joyent_include.sh
+
+        # All the files come from USB, so we need that mounted.
+        if !mount_usb ; then
+            echo "FATAL: Cannot find USB key." >/dev/console
+            exit 1;
+        fi
+
+        initial_script=$(grep "^initial_script=" /mnt/config 2>/dev/null | cut -d'=' -f2-)
+        if [ -n ${initial_script} ] && [ -e ${initial_script} ]; then
+            # Execute the script
+            ${initial_script}
+            result=$?
+            if [ ${result} -eq 2 ]; then
+                # we're rebooting, no need to start ur
+                echo "REBOOTING!" >> /dev/console
+                enable_ur="false"
+            elif [ ${result} -ne 0 ]; then
+                echo "WARNING: initial_script failed with exit code [${result}].  Not starting Ur."
+                enable_ur="false"
+            fi
+        fi
+    fi
+
     /joyent/ur-agent/ur-agent >/etc/svc/volatile/ur-agent.log 2>&1 &
-	;;
+    ;;
 
 'stop')
-	;;
+    ;;
 
 *)
-	echo "Usage: $0 { start | stop }"
-	exit $SMF_EXIT_ERR_FATAL
-	;;
+    echo "Usage: $0 { start | stop }"
+    exit $SMF_EXIT_ERR_FATAL
+    ;;
 esac
 exit $SMF_EXIT_OK
