OS-238 error out if we fail to create the dump device

diff --git a/usr/src/lib/brand/joyent/zone/svc-joyinit b/usr/src/lib/brand/joyent/zone/svc-joyinit
--- a/usr/src/lib/brand/joyent/zone/svc-joyinit
+++ b/usr/src/lib/brand/joyent/zone/svc-joyinit
@@ -58,8 +58,8 @@ case "$1" in
                 echo "REBOOTING!" >> /dev/console
                 enable_ur="false"
             elif [ ${result} -ne 0 ]; then
-                echo "WARNING: initial_script failed with exit code [${result}].  Not starting Ur."
-                enable_ur="false"
+                echo "WARNING: initial_script failed with exit code [${result}]."
+                exit $SMF_EXIT_ERR_FATAL
             fi
         fi
     fi
