PSARC 2004/368 Secure By Default 4875624 *syslogd* turn off UDP listener by default 5004374 Ship with remote services disabled by default 5016956 By default rpcbind should not listen for remote requests 5016975 By default snmpd/dx should not be enabled. 5016998 By default inetd should not listen for remote connections. 5017041 By default sendmail should not listen for remote connections 5046450 Create a greenline profile for Secure by Default installation 6267741 RFE: One-touch knob for outbound-only sendmail 6414308 syslogd could use some lint soap

diff --git a/usr/src/cmd/agents/snmp/snmprelayd/svc-snmpdx b/usr/src/cmd/agents/snmp/snmprelayd/svc-snmpdx
--- a/usr/src/cmd/agents/snmp/snmprelayd/svc-snmpdx
+++ b/usr/src/cmd/agents/snmp/snmprelayd/svc-snmpdx
@@ -19,28 +19,39 @@
 #
 # CDDL HEADER END
 #
-#	Copyright (c) 1984, 1986, 1987, 1988, 1989 AT&T
-#	  All Rights Reserved
-#
 # Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # ident	"%Z%%M%	%I%	%E% SMI"
+#
+# Start method script for the Sun Solstice Enterprise Master Agent
+#
 
-STARTLST="16boot.server"
+. /lib/svc/share/smf_include.sh
 
-INSDIR=${ROOT}/etc/rc3.d
+SNMP_CONFDIR=/etc/snmp/conf
 
-if [ ! -d ${INSDIR} ]
-then
-	mkdir ${INSDIR}
-	eval ${CH}chmod 755 ${INSDIR}
-	eval ${CH}chgrp sys ${INSDIR}
-	eval ${CH}chown root ${INSDIR}
+SNMP_RSRC=${SNMP_CONFDIR}/snmpdx.rsrc
+SNMP_BIN=/usr/lib/snmp/snmpdx
+
+if [ ! -f $SNMP_RSRC ]; then
+	echo "Configuration file $SNMP_RSRC does not exist. Not starting snmpdx"
+	exit $SMF_EXIT_ERR_CONFIG
 fi
-for f in ${STARTLST}
-do
-	name=`echo $f | sed -e 's/^..//'`
-	rm -f ${INSDIR}/S$f
-	ln ${ROOT}/etc/init.d/${name} ${INSDIR}/S$f
-done
+
+if [ ! -x $SNMP_BIN ]; then
+	echo "$SNMP_BIN not found. Not starting snmpdx"
+	exit $SMF_EXIT_ERR_CONFIG
+fi
+
+if /usr/bin/egrep -sv '^[	  ]*(#|$)' ${SNMP_RSRC} 2> /dev/null ; then
+	:
+else
+	# Do not start snmpdx if snmpdx.rsrc contents are
+	# trivial.
+	echo "$SNMP_RSRC contains no definitions. Not starting snmpdx."
+	exit $SMF_EXIT_ERR_CONFIG
+fi
+
+${SNMP_BIN}  -y -c ${SNMP_CONFDIR}
+exit $SMF_EXIT_OK
diff --git a/usr/src/cmd/syslogd/system-log b/usr/src/cmd/syslogd/system-log
--- a/usr/src/cmd/syslogd/system-log
+++ b/usr/src/cmd/syslogd/system-log
@@ -19,34 +19,80 @@
 #
 # CDDL HEADER END
 #
-#
 # Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # ident	"%Z%%M%	%I%	%E% SMI"
 
+OLD_CONF=/etc/default/syslogd
+
 . /lib/svc/share/smf_include.sh
 
-if [ -f /etc/syslog.conf -a -f /usr/sbin/syslogd ]; then
-	if smf_is_globalzone; then
-		#
-		# Before syslogd starts, save any messages from
-		# previous crash dumps so that messages appear
-		# in chronological order.
-		#
-		/usr/bin/savecore -m
-		if [ -r /etc/dumpadm.conf ]; then
-			. /etc/dumpadm.conf
-			[ -n "$DUMPADM_DEVICE" -a \
-		    	"x$DUMPADM_DEVICE" != xswap ] && \
-		    	/usr/bin/savecore -m -f $DUMPADM_DEVICE
+convert()
+{
+	svccfg -s svc:/system/system-log setprop config/log_from_remote = $1
+	if [ $? -ne 0 ]; then
+		svccfg -s svc:/system/system-log addpg config application
+		svccfg -s svc:/system/system-log \
+		    addpropvalue config/log_from_remote boolean: $1
+		if [ $? -ne 0 ] ; then
+			echo 'Failed to set remote syslog-logging'
+			exit $SMF_EXIT_ERR_CONFIG
 		fi
 	fi
-	if [ ! -f /var/adm/messages ]; then
-		/usr/bin/cp /dev/null /var/adm/messages
-		/usr/bin/chmod 0644 /var/adm/messages
-	fi
-	/usr/sbin/syslogd >/dev/msglog 2>&1 &
-else
+	echo "Incorporated ${OLD_CONF} settings into SMF. See syslogd(1m)."
+	awk '{
+		if ($1 ~ /^LOG_FROM_REMOTE=/) {
+			print "# LOG_FROM_REMOTE is now set using "
+			    "svccfg(1m), see syslog(1m).";
+		} else {
+			print $0;
+		}
+	}' ${OLD_CONF} >${OLD_CONF}.new && cp ${OLD_CONF}.new ${OLD_CONF}
+	rm -f ${OLD_CONF}.new
+}
+
+if [ ! -f /etc/syslog.conf ]; then
+	echo "/etc/syslog.conf is missing. Exiting."
 	exit $SMF_EXIT_ERR_CONFIG
 fi
+
+if [ ! -x /usr/sbin/syslogd ]; then
+	echo "Executable /usr/sbin/syslogd not found. Exiting"
+	exit $SMF_EXIT_ERR_CONFIG
+fi
+
+if smf_is_globalzone; then
+	#
+	# Before syslogd starts, save any messages from
+	# previous crash dumps so that messages appear
+	# in chronological order.
+	#
+	/usr/bin/savecore -m
+	if [ -r /etc/dumpadm.conf ]; then
+		. /etc/dumpadm.conf
+		[ -n "$DUMPADM_DEVICE" -a \
+	    	"x$DUMPADM_DEVICE" != xswap ] && \
+	    	/usr/bin/savecore -m -f $DUMPADM_DEVICE
+	fi
+fi
+if [ ! -f /var/adm/messages ]; then
+	/usr/bin/cp /dev/null /var/adm/messages
+	/usr/bin/chmod 0644 /var/adm/messages
+fi
+remote=`awk -F= '
+	/^LOG_FROM_REMOTE=[yY][Ee][Ss]/ {print "true"}
+	/^LOG_FROM_REMOTE=[Nn][Oo]/     {print "false"}' < ${OLD_CONF}`
+case ${remote} in
+"")
+    ;;
+"true"|"false")
+    convert ${remote}
+    ;;
+*)
+    echo "Unsupported value in for LOG_FROM_REMOTE in ${OLD_CONF}"
+    exit $SMF_EXIT_ERR_CONFIG
+    ;;
+esac
+
+/usr/sbin/syslogd >/dev/msglog 2>&1 &
