4027 remove CLOSED_BUILD 4028 remove CLOSED_IS_PRESENT 4029 remove tonic build bits Reviewed by: Andy Stormont <andyjstormont@gmail.com> Reviewed by: Richard Lowe <richlowe@richlowe.net> Approved by: Richard Lowe <richlowe@richlowe.net>

diff --git a/usr/src/Makefile b/usr/src/Makefile
--- a/usr/src/Makefile
+++ b/usr/src/Makefile
@@ -135,22 +135,20 @@ clobber_local:
 
 closedbins: bldtools $(ROOTDIRS) FRC
 	@CLOSED_ROOT="$$ON_CLOSED_BINS/root_$(MACH)$${RELEASE_BUILD+-nd}"; \
-	if [ "$$CLOSED_IS_PRESENT" = no ]; then \
-		if [ ! -d "$$CLOSED_ROOT" ]; then \
-			$(ECHO) "Error: if closed sources are not present," \
-			    "ON_CLOSED_BINS must point to closed binaries."; \
-			$(ECHO) "root_$(MACH)$${RELEASE_BUILD+-nd} is not" \
-			    "present in $$ON_CLOSED_BINS."; \
-			exit 1; \
-		fi; \
-		$(ECHO) "Copying closed binaries from $$CLOSED_ROOT"; \
-		(cd $$CLOSED_ROOT; \
-		    $(TAR) cfX - $(CODEMGR_WS)/exception_lists/closed-bins .) | \
-		    (cd $(ROOT); $(TAR) xBpf -); \
-		( cd $(ROOT); $(CTFSTRIP) $$(cd $$CLOSED_ROOT; $(FIND) \
-		    ./kernel ./usr/kernel ./platform/*/kernel -type f -a -perm -u+x | \
-		    $(EGREP) -vf $(CODEMGR_WS)/exception_lists/closed-bins) ); \
-	fi
+	if [ ! -d "$$CLOSED_ROOT" ]; then \
+		$(ECHO) "Error: ON_CLOSED_BINS must point to closed" \
+		    "binaries."; \
+		$(ECHO) "root_$(MACH)$${RELEASE_BUILD+-nd} is not" \
+		    "present in $$ON_CLOSED_BINS."; \
+		exit 1; \
+	fi; \
+	$(ECHO) "Copying closed binaries from $$CLOSED_ROOT"; \
+	(cd $$CLOSED_ROOT; \
+	    $(TAR) cfX - $(CODEMGR_WS)/exception_lists/closed-bins .) | \
+	    (cd $(ROOT); $(TAR) xBpf -); \
+	( cd $(ROOT); $(CTFSTRIP) $$(cd $$CLOSED_ROOT; $(FIND) \
+	    ./kernel ./usr/kernel ./platform/*/kernel -type f -a -perm -u+x | \
+	    $(EGREP) -vf $(CODEMGR_WS)/exception_lists/closed-bins) )
 
 #
 # Declare what parts can be built in parallel
@@ -213,10 +211,8 @@ check:	$(CHKHDRSUBDIRS) $(CHKMFSTSUBDIRS)
 # Cross-reference customization: skip all of the subdirectories that
 # don't contain actual source code.
 #
-$(CLOSED_BUILD)XRDIRS += ../closed
 XRPRUNE = pkg prototypes
 XRINCDIRS = uts/common head ucbhead
-$(CLOSED_BUILD)XRINCDIRS = uts/common ../closed/uts/common head ucbhead
 
 cscope.out tags: FRC
 	$(XREF) -f -x $@
