6807050 GNU linkonce sections can create duplicate and incompatible eh_frame FDE entries

diff --git a/usr/src/cmd/sgs/packages/common/checkinstall b/usr/src/cmd/sgs/packages/common/checkinstall
--- a/usr/src/cmd/sgs/packages/common/checkinstall
+++ b/usr/src/cmd/sgs/packages/common/checkinstall
@@ -1,13 +1,12 @@
 #
-# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # CDDL HEADER START
 #
 # The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 # or http://www.opensolaris.org/os/licensing.
@@ -22,8 +21,6 @@
 #
 # CDDL HEADER END
 #
-#ident	"%Z%%M%	%I%	%E% SMI"
-#
 
 if [ -d $BASEDIR/$SGSBACKUPDIR ];
 then
@@ -33,5 +30,19 @@ then
     echo "***"
     exit 1
 fi
+
+# As of Nevada build snv_104, we require the mmapobj() system call.
+# Installing on a system that lacks it will break rtld and brick the system.
+elfdump -sN.dynsym /lib/libc.so.1 | grep mmapobj > /dev/null
+if [ $? != 0 ];
+then
+    echo "***"
+    echo "*** System lacks required mmapobj() system call"
+    echo "*** Nevada snv_104 or newer is required."
+    echo "***"
+    exit 1
+fi
+
+
 
 exit 0
