PSARC 2006/647 PPD Manager 5100134 print/rfc1179 ends up by default in "offline" state 6236968 No documented way to add PPD file to ppdcache 6527759 Need to delete legacy print/cleanup service 6529794 lpsched not started after first local printer is added

diff --git a/usr/src/pkgdefs/SUNWpsr/postinstall b/usr/src/pkgdefs/SUNWpsr/postinstall
--- a/usr/src/pkgdefs/SUNWpsr/postinstall
+++ b/usr/src/pkgdefs/SUNWpsr/postinstall
@@ -2,9 +2,8 @@
 # CDDL HEADER START
 #
 # The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 # or http://www.opensolaris.org/os/licensing.
@@ -20,7 +19,7 @@
 # CDDL HEADER END
 #
 #
-# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 #ident	"%Z%%M%	%I%	%E% SMI"
@@ -30,10 +29,50 @@
 # If appropriate, enable this service.
 #
 BASEPREFIX=`echo $BASEDIR | sed "s/\//_/g"`
-FILENAME=`echo sunwpsr_lpsched"$BASEPREFIX" | cut -c 1-256`
-TMPFILE=/tmp/$FILENAME
-if [ -f $TMPFILE ]; then
+LPFILENAME=`echo sunwpsr_lpsched"$BASEPREFIX" | cut -c 1-256`
+LPTMPFILE=/tmp/$LPFILENAME
+if [ -f $LPTMPFILE ]; then
 	echo "/usr/sbin/svcadm enable application/print/server" >> \
 	    $BASEDIR/var/svc/profile/upgrade
-	rm $TMPFILE
+	rm $LPTMPFILE
 fi
+
+PPDFILENAME=`echo sunwpsr_ppd_cache_update"$BASEPREFIX" | cut -c 1-256`
+PPDTMPFILE=/tmp/$PPDFILENAME
+if [ -f $PPDTMPFILE ] ; then
+
+	# Enable the ppd-cache-update service.
+	echo "/usr/sbin/svcadm enable application/print/ppd-cache-update" >> \
+	    $BASEDIR/var/svc/profile/upgrade
+
+	# Ensure pre-existing printer configuration files with an
+	# old system PPD file delivery location are updated to
+	# reflect the newest location of PPD files.
+	NEW_PATH=/usr/share/ppd
+	if [ -d $NEW_PATH ] ; then
+		OLD_PATH=/usr/lib/lp/model/ppd/system
+		PNTRS=$BASEDIR/etc/lp/printers
+		for f in `/bin/find $PNTRS -name configuration 2>/dev/null` ; do
+		    /bin/grep ${OLD_PATH} ${f} >/dev/null 2>&1
+			if [ $? -eq 0 ] ; then
+				/bin/sed \
+		    -e "s;${OLD_PATH}/foomatic;${NEW_PATH}/SUNWfoomatic;g" \
+		    -e "s;${OLD_PATH}/gimp;${NEW_PATH}/SUNWgimp;g" \
+                    -e "s;${OLD_PATH}/hpijs;${NEW_PATH}/SUNWhpijs;g" \
+		    ${f} >/tmp/lp.$$
+				/bin/mv -f /tmp/lp.$$ ${f}
+			fi
+		done
+		rm $PPDTMPFILE
+	fi
+fi
+
+# This works around the problem of legacy cleanup service removal until
+# r.manifest is fixed to work on alternate pkg root.
+if [ "${PKG_INSTALL_ROOT:-/}" != "/" ] ; then
+	echo "/usr/sbin/svccfg delete -f svc:/application/print/cleanup" >> \
+	    $BASEDIR/var/svc/profile/upgrade
+	
+fi
+
+exit 0
