PSARC 2010/067 Interim modernization updates 6915312 ON should be able to build IPS packages natively 6281004 docbook.dtd is obsolete and unused 6490919 strange file in onnv-gate 6878498 update tools proto ${ROOT} to include ${MACH} and make nightly.sh copy it into parent repository 6888427 SVM packages should drop legacy objects 6893530 Some header files can be opened up 6903324 sharemgr should either use isaexec or not build 64-bit commands 6920651 mktpl will inadvertently reuse stale license files for empty license lists 6920674 svvs kmods should not be built during an open build Portions contributed by Rich Lowe <richlowe@richlowe.net>
--HG--
rename : usr/src/cmd/oamuser/user/stdprofile => usr/src/cmd/nsadmin/dot-profile.sh
rename : usr/src/cmd/nsadmin/profile => usr/src/cmd/nsadmin/etc-profile.sh
rename : usr/src/pkgdefs/common_files/i.manifest => usr/src/cmd/svc/common/i.manifest
rename : usr/src/pkgdefs/common_files/r.manifest => usr/src/cmd/svc/common/r.manifest
rename : usr/src/lib/brand/native/Makefile => usr/src/lib/brand/ipkg/Makefile
rename : usr/src/lib/brand/native/zone/Makefile => usr/src/lib/brand/ipkg/zone/Makefile
rename : usr/src/lib/brand/native/zone/SUNWblank.xml => usr/src/lib/brand/ipkg/zone/SUNWblank.xml
rename : usr/src/lib/brand/native/zone/SUNWdefault.xml => usr/src/lib/brand/ipkg/zone/SUNWdefault.xml
rename : usr/src/lib/brand/native/zone/config.xml => usr/src/lib/brand/ipkg/zone/config.xml
rename : usr/src/lib/brand/native/zone/platform.xml => usr/src/lib/brand/ipkg/zone/platform.xml
rename : usr/src/lib/brand/native/Makefile => usr/src/lib/brand/labeled/Makefile
rename : usr/src/lib/brand/native/zone/Makefile => usr/src/lib/brand/labeled/zone/Makefile
rename : usr/src/lib/brand/native/zone/config.xml => usr/src/lib/brand/labeled/zone/config.xml
rename : usr/src/lib/brand/native/zone/platform.xml => usr/src/lib/brand/labeled/zone/platform.xml
rename : usr/src/lib/brand/native/zone/common.ksh => usr/src/lib/brand/shared/common.ksh
rename : usr/src/lib/brand/native/zone/query.ksh => usr/src/lib/brand/shared/query.ksh
rename : usr/src/lib/brand/native/zone/uninstall.ksh => usr/src/lib/brand/shared/uninstall.ksh
rename : usr/src/pkgdefs/common_files/i.rbac => usr/src/lib/libsecdb/common/i.rbac
rename : usr/src/pkgdefs/common_files/r.rbac => usr/src/lib/libsecdb/common/r.rbac
rename : usr/src/pkgdefs/license_files/cr_ATT => usr/src/pkg/license_files/cr_ATT
rename : usr/src/pkgdefs/SUNWfipe/cr_Intel => usr/src/pkg/license_files/cr_Intel.SUNWfipe
rename : usr/src/pkgdefs/SUNWintgige/cr_Intel => usr/src/pkg/license_files/cr_Intel.SUNWintgige
rename : usr/src/pkgdefs/license_files/cr_Sun => usr/src/pkg/license_files/cr_Sun
rename : usr/src/pkgdefs/SUNWgrub/grubcredits => usr/src/pkg/license_files/grubcredits
rename : usr/src/pkgdefs/SUNWcsl/lic_AMD => usr/src/pkg/license_files/lic_AMD
rename : usr/src/pkgdefs/license_files/lic_CDDL => usr/src/pkg/license_files/lic_CDDL
rename : usr/src/pkgdefs/SUNWemlxs/lic_Emulex => usr/src/pkg/license_files/lic_Emulex
rename : usr/src/pkgdefs/license_files/lic_GPLv2 => usr/src/pkg/license_files/lic_GPLv2
rename : usr/src/pkgdefs/CPQary3/lic_HP => usr/src/pkg/license_files/lic_HP
rename : usr/src/tools/opensolaris/BINARYLICENSE.txt => usr/src/pkg/license_files/lic_OSBL
rename : usr/src/pkgdefs/license_files/lic_OSBL_preamble => usr/src/pkg/license_files/lic_OSBL_preamble
rename : usr/src/pkgdefs/SUNWqlc/lic_Qlogic => usr/src/pkg/license_files/lic_Qlogic
rename : usr/src/pkgdefs/SUNWhwdata/LICENSE => usr/src/pkg/license_files/lic_SUNWhwdata
rename : usr/src/pkgdefs/SUNWroute/copyright.in => usr/src/pkg/license_files/lic_SUNWroute
rename : usr/src/pkgdefs/SUNWgss/gss_license => usr/src/pkg/license_files/lic_gss
rename : usr/src/pkgdefs/license_files/license_in_headers => usr/src/pkg/license_files/license_in_headers
rename : usr/src/uts/intel/os/solaris.xpm.gz => usr/src/uts/intel/os/solaris.xpm

diff --git a/usr/src/cmd/ssh/etc/sshd b/usr/src/cmd/ssh/etc/sshd
--- a/usr/src/cmd/ssh/etc/sshd
+++ b/usr/src/cmd/ssh/etc/sshd
@@ -1,10 +1,11 @@
 #!/sbin/sh
 #
-# Copyright 2009 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2010 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 
 . /lib/svc/share/ipf_include.sh
+. /lib/svc/share/smf_include.sh
 
 SSHDIR=/etc/ssh
 KEYGEN="/usr/bin/ssh-keygen -q"
@@ -18,15 +19,30 @@ create_key()
 	keytype=$2
 
 	if [ ! -f $keypath ]; then
-		grep "^HostKey $keypath" $SSHDIR/sshd_config > /dev/null 2>&1
+		# 
+		# HostKey keywords in sshd_config may be preceded or
+		# followed by a mix of any number of space or tabs,
+		# and optionally have an = between keyword and
+		# argument.  We use two grep invocations such that we
+		# can match HostKey case insensitively but still have
+		# the case of the path name be significant, keeping
+		# the pattern somewhat more readable.
+		#
+		# The character classes below contain one literal
+		# space and one literal tab.
+		#
+		grep -i "^[ 	]*HostKey[ 	]*=\{0,1\}[ 	]*$keypath" \
+		    $SSHDIR/sshd_config | grep "$keypath" > /dev/null 2>&1
+
 		if [ $? -eq 0 ]; then
 			echo Creating new $keytype public/private host key pair
 			$KEYGEN -f $keypath -t $keytype -N ''
-			return $?
+			if [ $? -ne 0 ]; then
+				echo "Could not create $keytype key: $keypath"
+				exit $SMF_EXIT_ERR_CONFIG
+			fi
 		fi
 	fi
-
-	return 0
 }
 
 create_ipf_rules()
@@ -74,6 +90,14 @@ case $1 in
 	;;
 
 'start')
+	#
+	# If host keys don't exist when the service is started, create
+	# them; sysidconfig is not run in every situation (such as on
+	# the install media).
+	# 
+	create_key $SSHDIR/ssh_host_rsa_key rsa
+	create_key $SSHDIR/ssh_host_dsa_key dsa
+
 	/usr/lib/ssh/sshd
 	;;
 
