PSARC/2006/357 Crossbow - Network Virtualization and Resource Management 6498311 Crossbow - Network Virtualization and Resource Management 6402493 DLPI provider loopback behavior should be improved 6453165 move mac capabs definitions outside mac.h 6338667 Need ability to use NAT for non-global zones 6692884 several threads hung due to deadlock scenario between aggr and mac 6768302 dls: soft_ring_bind/unbind race can panic in thread_affinity_set with cpu_id == -1 6635849 race between lacp_xmit_sm() and aggr_m_stop() ends in panic 6742712 potential message double free in the aggr driver 6754299 a potential race between aggr_m_tx() and aggr_port_delete() 6485324 mi_data_lock recursively held when enabling promiscuous mode on an aggregation 6442559 Forwarding perf bottleneck due to mac_rx() calls 6505462 assertion failure after removing a port from a snooped aggregation 6716664 need to add src/dst IP address to soft ring fanout
--HG--
rename : usr/src/uts/common/io/dls/dls_soft_ring.c => usr/src/uts/common/io/mac/mac_soft_ring.c
rename : usr/src/uts/common/inet/ip/ip_cksum.c => usr/src/uts/common/os/ip_cksum.c
rename : usr/src/uts/common/inet/sctp_crc32.c => usr/src/uts/common/os/sctp_crc32.c
rename : usr/src/uts/common/sys/dls_soft_ring.h => usr/src/uts/common/sys/mac_soft_ring.h

diff --git a/usr/src/pkgdefs/SUNWcnetr/postinstall b/usr/src/pkgdefs/SUNWcnetr/postinstall
--- a/usr/src/pkgdefs/SUNWcnetr/postinstall
+++ b/usr/src/pkgdefs/SUNWcnetr/postinstall
@@ -109,6 +109,44 @@ if [ -f "${ORIG}" ]; then
 	removef -f $PKGINST > /dev/null 2>&1
 fi
 
+# Convert hostname.xxx and zonecfg vlan entries
+host_ifs=`ls -1 $rootprefix/etc | egrep -e '^hostname.|^hostname6.|^dhcp.'| \
+    cut -d . -f2 | sort -u` 
+
+zones=`zoneadm list -c | grep -v global`
+for zone in $zones
+do
+	zonecfg -z $zone info ip-type | grep exclusive >/dev/null
+	if [ $? -eq 0 ]; then
+		zif=`zonecfg -z $zone info net | grep physical | \
+		    nawk '{print $2}'`
+		zone_ifs="$zone_ifs $zif"
+	fi
+done
+
+ORIG=$BASEDIR/etc/dladm/datalink.conf
+for ifname in $host_ifs $zone_ifs
+do
+	grep $ifname $ORIG >/dev/null
+	if [ $? != 0 ]; then
+		phys=`echo $ifname | sed "s/[0-9]*$//"`
+		devnum=`echo $ifname | sed "s/$phys//g"`
+		if [ "$phys$devnum" != $ifname -o \
+		    -n "`echo $devnum | tr -d '[0-9]'`" ]; then
+			echo "skipping invalid interface $ifname"
+			continue
+		fi
+
+		vid=`expr $devnum / 1000`
+		inst=`expr $devnum % 1000`
+
+		if [ "$vid" != "0" ]; then
+			echo dladm create-vlan -l $phys$inst -v $vid \
+			    $ifname >> ${PKG_INSTALL_ROOT}/$UPGRADE_SCRIPT
+		fi
+	fi
+done
+
 #
 # Change permissions of public IKE certificates and CRLs
 # that may have been incorrectly created as private
