6570963 vscan: snas: Can't Enable vscan service after,disabling it while scan was in progress for few files 6599614 Log message says "vscan: (eng #) no socket, errno 24" when copying 1000 2k-files with 4 scan engines 6656150 vscan threading model should be revised to address system resource usage 6660667 Engine name is used directly as property group name without any prefix 6663788 SUNWvscanr needs to be split into SUNWvscanr and SUNWvscankr 6663792 links are required in /dev for the vscan pseudo device - to support non-global zones 6663812 attempt to start a second instance of vscand, first instance crashes 6672296 per-engine error counts not shown after vscan stats reset using vscanadm stats -z 6673579 vscan log file should be parsable and use utf8 6678058 If stats door file already exists when vscand starts up an initialization failure message is shown 6678525 vscand exits on SIGPIPE 6679808 Interupted read/write (EINTR) to scan engine can cause invalid data to be exchanged 6681465 Core file generated while adding and performing virus scan operations over nfs mount 6681675 Connection remains in ESTABLISHED State for long time, after scan engine goes down. 6684670 vscand should maintain connections with scan engines instead of connecting per request

diff --git a/usr/src/pkgdefs/SUNWvscankr/postinstall b/usr/src/pkgdefs/SUNWvscankr/postinstall
--- a/usr/src/pkgdefs/SUNWvscankr/postinstall
+++ b/usr/src/pkgdefs/SUNWvscankr/postinstall
@@ -28,19 +28,32 @@
 PATH="/usr/bin:/usr/sbin:${PATH}"
 export PATH
 
-PKG_NAME=SUNWvscanr
-DMON=vscand
+PKG_NAME=SUNWvscankr
+DRV=vscan
+DRVPERM='* 0640 root sys'
+
+ADD_DRV=/usr/sbin/add_drv
 
 #
-# Make sure that the VSCAN client daemon (vscand) is not
-# running before removing this package.
+# Check if the BASEDIR option is needed
 #
-if [ "${PKG_INSTALL_ROOT:-/}" = "/" ]; then
-	/usr/bin/pgrep -x "${DMON}" >/dev/null
-	if [ $? -ne 1 ]; then
-		echo "\nUnable to remove ${PKG_NAME}: the vscan service is enabled"
-		echo "Disable vscan service and try again:"
-		echo "\tsvcadm disable system/filesystem/vscan\n"
+if [ "${BASEDIR}" = "/" ]; then
+	ADD_DRV_FLAGS=""
+	NAME_TO_MAJOR="/etc/name_to_major"
+else
+	ADD_DRV_FLAGS="-b ${BASEDIR}"
+	NAME_TO_MAJOR="${BASEDIR}/etc/name_to_major"
+fi
+
+#
+# Make sure add_drv has not been previously executed before attempting
+# to add the driver
+#
+grep "^${DRV} " ${NAME_TO_MAJOR} > /dev/null 2>&1
+if [ $? -ne 0 ]; then
+	${ADD_DRV} ${ADD_DRV_FLAGS} -m "${DRVPERM}" ${DRV}
+	if [ $? -ne 0 ]; then
+		echo "${PKG_NAME}: add_drv ${DRV} failed\n" >&2
 		exit 1
 	fi
 fi
diff --git a/usr/src/pkgdefs/SUNWvscankr/preremove b/usr/src/pkgdefs/SUNWvscankr/preremove
--- a/usr/src/pkgdefs/SUNWvscankr/preremove
+++ b/usr/src/pkgdefs/SUNWvscankr/preremove
@@ -28,7 +28,8 @@
 PATH="/usr/bin:/usr/sbin:${PATH}"
 export PATH
 
-PKG_NAME=SUNWvscanr
+PKG_NAME=SUNWvscankr
+DRV=vscan
 DMON=vscand
 
 #
@@ -41,6 +42,25 @@ if [ "${PKG_INSTALL_ROOT:-/}" = "/" ]; then
 		echo "\nUnable to remove ${PKG_NAME}: the vscan service is enabled"
 		echo "Disable vscan service and try again:"
 		echo "\tsvcadm disable system/filesystem/vscan\n"
+		exit 1
+	fi
+fi
+
+#
+# Remove driver, if this has not already been done
+#
+BASEDIR=${BASEDIR:-/}
+if [ "$BASEDIR" = "/" ]; then
+	REM_DRV="rem_drv"
+else
+	REM_DRV="rem_drv -b ${BASEDIR}"
+fi
+
+grep "^${DRV}" ${BASEDIR}/etc/name_to_major > /dev/null 2>&1
+if [ $? -eq 0 ]; then
+	${REM_DRV} ${DRV}
+	if [ $? -ne 0 ]; then
+		echo "${PKG_NAME}: rem_drv ${DRV} failed\n" >&2
 		exit 1
 	fi
 fi
