PSARC/2005/090 Resource pools service FMRIs 4988841 Storing the poold pid in the pools configuration is wrong 5010753 pool_start_poold() has suspicious execl invocation 5063672 Need to be able to install zones without bringing in java 6215817 poold could be an SMF service 6218168 libpool query APIs require error code clarification 6219460 poolcfg script file syntax problem with create command: cannot load configuration 6357203 poold should check for EINTR when handling signals

diff --git a/usr/src/pkgdefs/SUNWpoold/preremove b/usr/src/pkgdefs/SUNWpoold/preremove
--- a/usr/src/pkgdefs/SUNWpoold/preremove
+++ b/usr/src/pkgdefs/SUNWpoold/preremove
@@ -2,9 +2,8 @@
 # CDDL HEADER START
 #
 # The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 # or http://www.opensolaris.org/os/licensing.
@@ -24,19 +23,19 @@
 # Use is subject to license terms.
 #
 #pragma ident	"%Z%%M%	%I%	%E% SMI"
+
 #
-
-include ../Makefile.com
-
-DATAFILES += \
-	i.manifest	\
-	r.manifest
-
-.KEEP_STATE:
-
-all: $(FILES) depend preremove postinstall
-
-install: all pkg
-
-include ../Makefile.targ
-
+# Make sure that dynamic pools are not enabled before removing this package.
+#
+if [ "${PKG_INSTALL_ROOT:-/}" = "/" ]; then
+	if [ -x /usr/bin/svcs ]; then
+		STATE=`/usr/bin/svcs -Ho STA svc:/system/pools/dynamic`
+		if [ $? -eq 0 ]; then
+			if [ "$STATE" != "DIS" ]; then
+				echo "ERROR: unable to remove package" \
+					"while dynamic pools are enabled."
+				exit 1
+			fi
+		fi
+	fi
+fi
