OS-7685 smartos-live overlay should be merged into illumos-joyent Reviewed by: Jerry Jelinek <jerry.jelinek@joyent.com> Reviewed by: Mike Gerdts <mike.gerdts@joyent.com> Approved by: Mike Gerdts <mike.gerdts@joyent.com>

diff --git a/usr/src/cmd/svc/milestone/fs-root b/usr/src/cmd/svc/milestone/fs-root
--- a/usr/src/cmd/svc/milestone/fs-root
+++ b/usr/src/cmd/svc/milestone/fs-root
@@ -22,6 +22,7 @@
 #
 # Copyright (c) 1992, 2010, Oracle and/or its affiliates. All rights reserved.
 # Copyright 2015 Nexenta Systems, Inc. All rights reserved.
+# Copyright 2016 Joyent, Inc.
 #
 
 # Make sure that the libraries essential to this stage of booting can be found.
@@ -64,92 +65,27 @@ if smf_is_nonglobalzone; then
 	exit $SMF_EXIT_OK
 fi
 
+/sbin/mount -F ufs -o remount,rw,nologging /devices/ramdisk:a /
+/usr/sbin/lofiadm -X -a /usr.lgz
+
 #
-# Root is already mounted (by the kernel), but still needs to be
-# checked, possibly remounted and entered into mnttab.  First
-# mount /usr if it is a separate file system.  If the file system
-# type is something other than zfs, mount it read-only.  This must
-# be done first to allow utilities such as fsck and setmnt to
-# reside on /usr minimizing the space required by the root file
-# system.
+# Prior to mounting /usr, devfsadm is not yet available.  As such, we must
+# locate the lofi block device node in /devices rather than in /dev.  This
+# path has changed over time so we try both the old (pre-partition support)
+# and new paths.
 #
-readvfstab "/usr" < $vfstab
-if [ -n "$mountp" ]; then
-	if [ "$fstype" = zfs ]; then
-		mountfs - /usr $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
-	else
-		#
-		# Must use -o largefiles here to ensure the
-		# read-only mount does not fail as a result of
-		# having a large file present on /usr. This gives
-		# fsck a chance to fix up the largefiles flag
-		# before we remount /usr read-write.
-		#
-		if [ "x$mntopts" = x- ]; then
-			mntopts='ro,largefiles'
-		else
-			checkopt largefiles $mntopts
-			if [ "x$option" != xlargefiles ]; then
-				mntopts="largefiles,$mntopts"
-			fi
-
-			checkopt ro $mntopts
-			if [ "x$option" != xro ]; then
-				mntopts="ro,$mntopts"
-			fi
-
-			#
-			# Requesting logging on a read-only mount
-			# causes errors to be displayed, so remove
-			# "logging" from the list of options for now.
-			# The read-write mount performed later will
-			# specify the logging option if appropriate.
-			#
-
-			checkopt logging $mntopts
-			if [ "x$option" = xlogging ]; then
-				mntopts="$otherops"
-			fi
-		fi
-
-		mountfs -O /usr $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
+lofi_devices_path='/devices/pseudo/lofi@1:disk'
+if [ ! -b "$lofi_devices_path" ]; then
+	lofi_devices_path='/devices/pseudo/lofi@0:1'
+	if [ ! -b "$lofi_devices_path" ]; then
+		echo 'could not locate lofi block device in /devices' >&2
+		exit $SMF_EXIT_ERR_FATAL
 	fi
 fi
 
-#
-# if we are booted from zfs, the /usr mount probably won't be a
-# legacy mount.  Use the standard zfs mount command instead.
-
-readmnttab "/" < /etc/mnttab
-if [ "$fstype" = zfs ]; then
-	mountp=`/sbin/zfs get -H -o value mountpoint $special/usr 2>/dev/null`
-	#
-	# if mountp = /usr, there is a non-legacy mount of /usr
-	# in the boot environment being booted.
-	#
-	if [ "x$mountp" = "x/usr" ] ; then
-		/sbin/zfs mount $special/usr
-		if [ $? != 0 ] ; then
-				msg='zfs-mount failed'
-				echo $msg
-				echo "$SMF_FMRI:" $msg >/dev/msglog
-		 	exit $SMF_EXIT_ERR_FATAL
-		fi
-	fi
-fi
-
-#
-# Also mount /boot now so that things like keymap.sh can access
-# boot properties through eeprom.  Readonly isn't required because
-# /boot (and other pcfs filesystems) aren't fsck'ed at boot yet.
-# Also, we don't account for caching /boot as it must be on a local
-# disk.  So what's in vfstab is fine as it stands; just look to see
-# if it's there and avoid the mount if not.
-#
-readvfstab "/boot" < $vfstab
-
-if [ -n "$mountp" ]; then
-	mountfs - /boot $fstype $mntopts - || exit $SMF_EXIT_ERR_FATAL
+if ! /sbin/mount -F ufs -o ro "$lofi_devices_path" /usr; then
+	echo "could not mount /usr from $lofi_devices_path" >&2
+	exit $SMF_EXIT_ERR_FATAL
 fi
 
 #
diff --git a/usr/src/cmd/syslogd/system-log b/usr/src/cmd/syslogd/system-log
--- a/usr/src/cmd/syslogd/system-log
+++ b/usr/src/cmd/syslogd/system-log
@@ -21,10 +21,12 @@
 #
 # Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
+# Copyright 2016, Joyent, Inc.  All rights reserved.
 #
-# ident	"%Z%%M%	%I%	%E% SMI"
 
 OLD_CONF=/etc/default/syslogd
+DFLT_SUM="7c87d765805cc45a0dad9fb5c86cc4f2"
+CONF_SUM="$DFLT_SUM"
 
 . /lib/svc/share/smf_include.sh
 
@@ -52,14 +54,72 @@ convert()
 	rm -f ${OLD_CONF}.new
 }
 
-if [ ! -f /etc/syslog.conf ]; then
-	echo "/etc/syslog.conf is missing. Exiting."
-	exit $SMF_EXIT_ERR_CONFIG
+#
+# If the rsyslog.conf file doesn't exist and the syslog.conf file has not
+# been customized, generate the default rsyslog.conf.
+#
+generate_rsyslog_conf()
+{
+	if [ ! -f /etc/syslog.conf ]; then
+		return
+	fi
+
+	CONF_SUM=`nawk '{
+	    if (substr($1, 1, 1) != "#" && NF != 0) print $0
+	    }' /etc/syslog.conf | sum -x md5`
+
+	if [ "$CONF_SUM" != "$DFLT_SUM" ]; then
+		return
+	fi
+
+	cat <<-DONE >/etc/rsyslog.conf
+	#
+	# Sample rsyslog configuration file
+	#
+
+	$ModLoad immark
+	$ModLoad imsolaris
+	$ModLoad imtcp
+	$ModLoad imudp
+
+	*.err;kern.notice;auth.notice			/dev/sysmsg
+	*.err;kern.debug;daemon.notice;mail.crit	/var/adm/messages
+
+	*.alert;kern.err;daemon.err			operator
+	*.alert						root
+
+	*.emerg						*
+
+	mail.debug					/var/log/syslog
+
+	auth.info					/var/log/auth.log
+	mail.info					/var/log/postfix.log
+	DONE
+}
+
+if [ ! -f /etc/rsyslog.conf -a -x /usr/sbin/rsyslogd ]; then
+	generate_rsyslog_conf
 fi
 
-if [ ! -x /usr/sbin/syslogd ]; then
-	echo "Executable /usr/sbin/syslogd not found. Exiting"
-	exit $SMF_EXIT_ERR_CONFIG
+if [ -f /etc/rsyslog.conf ]; then
+	if [ ! -x /usr/sbin/rsyslogd ]; then
+		echo "Executable /usr/sbin/rsyslogd not found or not executable. Exiting."
+		exit $SMF_EXIT_ERR_CONFIG
+	fi
+else
+	#
+	# Fall back to old syslogd
+	#
+	echo "/etc/rsyslog.conf is missing. Using syslogd instead."
+	if [ ! -f /etc/syslog.conf ]; then
+		echo "/etc/syslog.conf is missing. Exiting."
+		exit $SMF_EXIT_ERR_CONFIG
+	fi
+
+	if [ ! -x /usr/sbin/syslogd ]; then
+		echo "Executable /usr/sbin/syslogd not found or not executable. Exiting."
+		exit $SMF_EXIT_ERR_CONFIG
+	fi
 fi
 
 if smf_is_globalzone; then
@@ -80,6 +140,27 @@ if [ ! -f /var/adm/messages ]; then
 	/usr/bin/cp /dev/null /var/adm/messages
 	/usr/bin/chmod 0644 /var/adm/messages
 fi
+
+if [ -f /etc/rsyslog.conf ]; then
+	#
+	# If we have a config file for the old syslogd, only run rsyslogd
+	# if there are no customizations in the old syslog.conf file.
+	#
+	if [ -f /etc/syslog.conf ]; then
+		CONF_SUM=`nawk '{
+		    if (substr($1, 1, 1) != "#" && NF != 0) print $0
+		    }' /etc/syslog.conf | sum -x md5`
+	fi
+
+	if [ "$CONF_SUM" == "$DFLT_SUM" ]; then
+		/usr/sbin/rsyslogd -c5 -n &
+		exit $SMF_EXIT_OK
+	fi
+fi
+
+#
+# Run the old syslogd
+#
 remote=`awk -F= '
 	/^LOG_FROM_REMOTE=[yY][Ee][Ss]/ {print "true"}
 	/^LOG_FROM_REMOTE=[Nn][Oo]/     {print "false"}' < ${OLD_CONF}`
@@ -96,3 +177,10 @@ case ${remote} in
 esac
 
 /usr/sbin/syslogd >/dev/msglog 2>&1 &
+
+if [ -f /etc/rsyslog.conf ]; then
+	logger -p daemon.err \
+	    "Not using rsyslogd because there is a custom /etc/syslog.conf file"
+fi
+
+exit $SMF_EXIT_OK
