PSARC 2008/168 Support for ZFS property value canmount=noauto 6661070 need canmount=noauto option for datasets to allow mount point to be set, but no mount done 6664570 need support for zfs canmount=noauto property in smf scripts

diff --git a/usr/src/cmd/svc/milestone/fs-usr b/usr/src/cmd/svc/milestone/fs-usr
--- a/usr/src/cmd/svc/milestone/fs-usr
+++ b/usr/src/cmd/svc/milestone/fs-usr
@@ -37,11 +37,18 @@
 #
 /sbin/swapadd -1
 
+rootiszfs=0
+# get the fstype of root
+readmnttab / </etc/mnttab
+if [ "$fstype" = zfs ] ; then
+	rootiszfs=1
+fi
+
 #
 # Check and remount the / (root) file system.
 # For NFS mounts, force the llock option on.
 #
-if smf_is_globalzone; then
+if smf_is_globalzone && [ $rootiszfs = 0 ]; then
 	readvfstab / < $vfstab
 	checkfs $fsckdev $fstype $mountp || exit $SMF_EXIT_ERR_FATAL
 	checkopt "llock" $mntopts
@@ -63,33 +70,36 @@ fi
 
 #
 # Check and remount the /usr file system (formerly mounted read-only).
+# Unless root is zfs, in which case we've already mounted /usr read-write
 #
-readvfstab /usr < $vfstab
-if [ "$mountp" ]; then
-	if [ "$fstype" = cachefs ]; then
-		mountfs -O $mountp cachefs $mntopts $special ||
-		    exit $SMF_EXIT_ERR_FATAL
-	else
-		checkopt ro $mntopts
-		if [ "x$option" != xro ]; then
-			checkfs $fsckdev $fstype $mountp ||
+if [ "$rootiszfs" = 0 ] ; then
+	readvfstab /usr < $vfstab
+	if [ "$mountp" ]; then
+		if [ "$fstype" = cachefs ]; then
+			mountfs -O $mountp cachefs $mntopts $special ||
 			    exit $SMF_EXIT_ERR_FATAL
-			if [ "x$mntopts" != x- ]; then
-				mntopts="remount,$mntopts"
-			else
-				mntopts="remount"
+		else
+			checkopt ro $mntopts
+			if [ "x$option" != xro ]; then
+				checkfs $fsckdev $fstype $mountp ||
+				    exit $SMF_EXIT_ERR_FATAL
+				if [ "x$mntopts" != x- ]; then
+					mntopts="remount,$mntopts"
+				else
+					mntopts="remount"
+				fi
+
+				# if usr dev is a read-only metadevice then fail
+				case $special in
+				/dev/md/dsk/*)
+					dd if=/dev/null of=$special count=0 \
+					    >/dev/null 2>&1 || exit $SMF_EXIT_ERR_FATAL
+					;;
+				esac
+
+				mountfs - /usr $fstype $mntopts - ||
+				    exit $SMF_EXIT_ERR_FATAL
 			fi
-
-			# if usr dev is a read-only metadevice then fail
-			case $special in
-			/dev/md/dsk/*)
-				dd if=/dev/null of=$special count=0 \
-				    >/dev/null 2>&1 || exit $SMF_EXIT_ERR_FATAL
-				;;
-			esac
-
-			mountfs - /usr $fstype $mntopts - ||
-			    exit $SMF_EXIT_ERR_FATAL
 		fi
 	fi
 fi
