PSARC 2006/552 Quagga SMF Modifications 6312914 routeadm needs to support smf-based routing services 6440342 remove redundancies in smf-related makefiles by moving manifest rules to usr/src/cmd/Makefile.targ
--HG--
rename : usr/src/cmd/cmd-inet/usr.sbin/in.rdisc.c => usr/src/cmd/cmd-inet/usr.sbin/in.rdisc/in.rdisc.c
rename : usr/src/cmd/cmd-inet/usr.sbin/routeadm.c => usr/src/cmd/cmd-inet/usr.sbin/routeadm/routeadm.c
rename : deleted_files/usr/src/cmd/volmgt/etc/Makefile => usr/src/cmd/volmgt/etc/Makefile

diff --git a/usr/src/cmd/svc/milestone/net-init b/usr/src/cmd/svc/milestone/net-init
--- a/usr/src/cmd/svc/milestone/net-init
+++ b/usr/src/cmd/svc/milestone/net-init
@@ -26,78 +26,29 @@
 # ident	"%Z%%M%	%I%	%E% SMI"
 #
 # This is the second phase of TCP/IP configuration.  The first part is
-# run by the /lib/svc/method/net-physical script (the svc:/network/physical
-# service) and includes configuring the interfaces and setting the machine's
-# hostname.  This script (the svc:/network/initial service), does all
-# configuration that can be done before name services are started. This
-# includes configuring IP routing, and setting any tunable parameters.
-# The third part, run by the /lib/svc/method/net-svc script (the
-# svc:/network/service service), does all configuration that may require
-# name services.  This includes a final re-configuration of the interfaces.
+# run by the svc:/network/physical service and includes configuring the
+# interfaces and setting the machine's hostname.  The svc:/network/initial
+# service does all configuration that can be done before name services are
+# started, bar configuring IP routing (this is carried out by the
+# svc:/network/routing-setup service).  The final part, run by the
+# svc:/network/service service,  does all configuration that may require
+# name services.  This includes a final re-configuration of the
+# interfaces.
 #
 
 . /lib/svc/share/smf_include.sh
 
-case "$1" in
-'start')
-	#
-	# In a zone we need this service to be up, but all of the work
-	# it tries to do is irrelevant (and will actually lead to the service
-	# failing if we try to do it), so just bail out.
-	#
-	smf_is_globalzone || exit $SMF_EXIT_OK
-
-	;; # Fall through -- rest of script is the initialization code
-
-'stop')
-	smf_is_globalzone || exit $SMF_EXIT_OK
-
-	#
-	# If we were routing dynamically, we will note this with
-	# the .dynamic_routing file, so that we can leave the routes
-	# in place without thinking they're static route entries
-	# when we come back into states 2 or 3.
-	#
-	if /usr/bin/pgrep -x -u 0 'in.routed|in.rdisc' >/dev/null 2>&1; then
-		/usr/bin/pkill -z global -x -u 0 'in.routed|in.rdisc'
-		> /etc/.dynamic_routing
-	fi
-	/usr/bin/pkill -z global -x -u 0 'in.ndpd|in.ripngd'
-	exit $SMF_EXIT_OK
-	;;
-
-*)
-	echo "Usage: $0 { start | stop }"
-	exit 1
-	;;
-esac
+#
+# In a zone we need this service to be up, but all of the work
+# it tries to do is irrelevant (and will actually lead to the service
+# failing if we try to do it), so just bail out.
+#
+smf_is_globalzone || exit $SMF_EXIT_OK
 
 # Configure IPv6 Default Address Selection.
 if [ -f /etc/inet/ipaddrsel.conf ]; then
 	/usr/sbin/ipaddrsel -f /etc/inet/ipaddrsel.conf
 fi
-
-/usr/sbin/ifconfig -a6u >/etc/svc/volatile/ifconfig.$$
-numv6ifs=`/usr/bin/grep -c inet6 /etc/svc/volatile/ifconfig.$$`
-if  [ $numv6ifs -gt 1 ]; then
-	#
-	# Add a static route for multicast packets out of a link-local
-	# interface, although would like to specify multicast interface using
-	# an interface name!
-	#
-	set -- `/usr/bin/awk '
-		/inet6 fe80:/ {
-			print substr($2, 1, index($2, "/") - 1)
-		}' /etc/svc/volatile/ifconfig.$$`
-
-	if [ -n "$1" ]; then
-		echo "Setting default IPv6 interface for multicast:" \
-		    "add net ff00::/8: gateway $1"
-		/usr/sbin/route -n add -interface -inet6 "ff00::/8" "$1" \
-		    >/dev/null
-	fi
-fi
-/usr/bin/rm -f /etc/svc/volatile/ifconfig.$$
 
 #
 # Now that /usr is mounted, see if in.mpathd needs to be started by firing it
@@ -146,105 +97,6 @@ unset encr
 if [ $TCP_STRONG_ISS ]; then
 	/usr/sbin/ndd -set /dev/tcp tcp_strong_iss $TCP_STRONG_ISS
 fi
-
-#
-# Configure default IPv4 routers using the local "/etc/defaultrouter"
-# configuration file.  The file can contain the hostnames or IP
-# addresses of one or more default routers.  If hostnames are used,
-# each hostname must also be listed in the local "/etc/hosts" file
-# because NIS and NIS+ are not running at the time that this script is
-# run.  Each router name or address is listed on a single line by
-# itself in the file.  Anything else on that line after the router's
-# name or address is ignored.  Lines that begin with "#" are
-# considered comments and ignored.
-#
-# The default routes listed in the "/etc/defaultrouter" file will
-# replace those added by the kernel during diskless booting.  An
-# empty "/etc/defaultrouter" file will cause the default route
-# added by the kernel to be deleted.
-#
-# Note that the default router file is ignored if we received routes
-# from a DHCP server.  Our policy is to always trust DHCP over local
-# administration.
-#
-smf_netstrategy
-
-if [ "$_INIT_NET_STRATEGY" = "dhcp" ] && [ -n "`/sbin/dhcpinfo Router`" ]; then
-	defrouters=`/sbin/dhcpinfo Router`
-elif [ -f /etc/defaultrouter ]; then
-	defrouters=`/usr/bin/grep -v \^\# /etc/defaultrouter | \
-	    /usr/bin/awk '{print $1}'`
-	if [ -n "$defrouters" ]; then
-		#
-		# We want the default router(s) listed in /etc/defaultrouter
-		# to replace the one added from the BOOTPARAMS WHOAMI response
-		# but we must avoid flushing the last route between the running
-		# system and its /usr file system.
-		#
-
-		# First, remember the original route.
-		shift $#
-		set -- `/usr/bin/netstat -rn -f inet | /usr/bin/grep '^default'`
-		route_IP="$2"
-
-		#
-		# Next, add those from /etc/defaultrouter.  While doing this,
-		# if one of the routes we add is for the route previously
-		# added as a result of the BOOTPARAMS response, we will see
-		# a message of the form:
-		#	"add net default: gateway a.b.c.d: entry exists"
-		#
-		do_delete=yes
-		for router in $defrouters; do
-			set -- `/usr/sbin/route -n add default -gateway $router`
-			[ $? -ne 0 -a "x$5" = "x$route_IP:" ] && do_delete=no
-		done
-
-		#
-		# Finally, delete the original default route unless it was
-		# also listed in the defaultrouter file.
-		#
-		if [ -n "$route_IP" -a $do_delete = yes ]; then
-			/usr/sbin/route -n delete default -gateway $route_IP \
-			    >/dev/null
-		fi
-	else
-		/usr/sbin/route -fn > /dev/null
-	fi
-else
-	defrouters=
-fi
-
-#
-# Use routeadm(1M) to configure forwarding and launch routing daemons for
-# IPv4 and IPv6 based on preset values.  These settings only apply to the
-# global zone.  For IPv4 dynamic routing, the system will default to
-# disabled if a default route was previously added via BOOTP, DHCP, or
-# the /etc/defaultrouter file.  routeadm also starts in.ndpd.
-#
-if [ ! -f /etc/.dynamic_routing ] && [ -z "$defrouters" ]; then
-	#
-	# No default routes were setup by "route" command above.
-	# Check the kernel routing table for any other default
-	# routes.
-	#
-	/usr/bin/netstat -rn -f inet | \
-	    /usr/bin/grep default >/dev/null 2>&1 && defrouters=yes
-fi
-[ -f /etc/.dynamic_routing ] && /usr/bin/rm -f /etc/.dynamic_routing
-if [ -z "$defrouters" ]; then
-	routeadmstr="-e ipv4-routing"
-else
-	routeadmstr="-d ipv4-routing"
-fi
-#
-# The -b option used here tells routeadm that the ipv4-routing
-# option in $routeadmstr is the boot-time default.  The
-# boot-time default is used if the administrator has not
-# explicitly enabled or disabled ipv4-routing using the -e or
-# -d routeadm option.
-#
-/usr/sbin/routeadm -u -b $routeadmstr
 
 #
 # In spite of global policy, there may be a need for IPsec because of
@@ -336,32 +188,6 @@ if [ -n "$interface_names" ]; then
 		done
 		echo "."
 	)
-fi
-
-#
-# Set 6to4 Relay Router communication support policy and, if applicable,
-# the destination Relay Router IPv4 address.  See /etc/default/inetinit for
-# setting and further info on ACCEPT6TO4RELAY and RELAY6TO4ADDR.
-# If ACCEPT6TO4RELAY=NO, the default value in the kernel will
-# be used.
-#
-ACCEPT6TO4RELAY=`echo "$ACCEPT6TO4RELAY" | /usr/bin/tr '[A-Z]' '[a-z]'`
-if [ "$ACCEPT6TO4RELAY" = yes ]; then
-        if [ "$RELAY6TO4ADDR" ]; then
-                /usr/sbin/6to4relay -e -a $RELAY6TO4ADDR
-        else
-                /usr/sbin/6to4relay -e
-        fi
-fi
-
-#
-# Read /etc/inet/static_routes and add each route.
-#
-if [ -f /etc/inet/static_routes ]; then
-	echo "Adding persistent routes:"
-	/usr/bin/egrep -v "^(#|$)" /etc/inet/static_routes | while read line; do
-		/usr/sbin/route add $line
-	done
 fi
 
 # Clear exit status.
