PSARC/2006/163 SMF_ZONENAME variable for smf_method(5) 6392792 calls to zonename(1) should be standardized, minimized

diff --git a/usr/src/cmd/pools/poold/svc-poold b/usr/src/cmd/pools/poold/svc-poold
--- a/usr/src/cmd/pools/poold/svc-poold
+++ b/usr/src/cmd/pools/poold/svc-poold
@@ -20,7 +20,7 @@
 # CDDL HEADER END
 #
 #
-# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # ident	"%Z%%M%	%I%	%E% SMI"
@@ -30,18 +30,22 @@
 
 . /lib/svc/share/smf_include.sh
 
-check_requirements () {
-	if [ ! -x /sbin/zonename ] || [ ! -x /usr/lib/pool/poold ] ||
-	    [ "${_INIT_ZONENAME:=`/sbin/zonename`}" != "global" ]; then
-		exit $SMF_EXIT_ERR_FATAL
-	fi
-}
+if [ ! -x /usr/lib/pool/poold ]; then
+	echo "/usr/lib/pool/poold not found or not executable"
+	exit $SMF_EXIT_ERR_FATAL
+fi
 
-check_requirements
+if smf_is_nonglobalzone; then
+	echo "poold cannot be run in non-global zones"
+	exit $SMF_EXIT_ERR_FATAL
+fi
+
 case "$1" in
 'start')
 	/usr/lib/pool/poold
-	if [ $? -ne 0 ]; then
+	err=$?
+	if [ $err -ne 0 ]; then
+		echo "poold failed to start: error $err"
 		exit $SMF_EXIT_ERR_FATAL
 	fi
 	;;
diff --git a/usr/src/cmd/pools/svc-pools b/usr/src/cmd/pools/svc-pools
--- a/usr/src/cmd/pools/svc-pools
+++ b/usr/src/cmd/pools/svc-pools
@@ -20,7 +20,7 @@
 # CDDL HEADER END
 #
 #
-# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # ident	"%Z%%M%	%I%	%E% SMI"
@@ -30,14 +30,16 @@
 
 . /lib/svc/share/smf_include.sh
 
-check_requirements () {
-	if [ ! -x /sbin/zonename ] || [ ! -x /usr/sbin/pooladm ] ||
-	    [ "${_INIT_ZONENAME:=`/sbin/zonename`}" != "global" ]; then
-		exit $SMF_EXIT_ERR_FATAL
-	fi
-}
+if [ ! -x /usr/sbin/pooladm ]; then
+	echo "/usr/sbin/pooladm not found or not executable"
+	exit $SMF_EXIT_ERR_FATAL
+fi
 
-check_requirements
+if smf_is_nonglobalzone; then
+	echo "pools service is only available in the global zone"
+	exit $SMF_EXIT_ERR_FATAL
+fi
+
 case "$1" in
 'start')
 	/usr/sbin/pooladm -e
diff --git a/usr/src/cmd/svc/milestone/boot-archive b/usr/src/cmd/svc/milestone/boot-archive
--- a/usr/src/cmd/svc/milestone/boot-archive
+++ b/usr/src/cmd/svc/milestone/boot-archive
@@ -3,9 +3,8 @@
 # CDDL HEADER START
 #
 # The contents of this file are subject to the terms of the
-# Common Development and Distribution License, Version 1.0 only
-# (the "License").  You may not use this file except in compliance
-# with the License.
+# Common Development and Distribution License (the "License").
+# You may not use this file except in compliance with the License.
 #
 # You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
 # or http://www.opensolaris.org/os/licensing.
@@ -21,10 +20,15 @@
 # CDDL HEADER END
 #
 #
-# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
+# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
 # Use is subject to license terms.
 #
 # ident	"%Z%%M%	%I%	%E% SMI"
+
+#
+# Check the boot archive content against root filesystem.
+# Return failure if they differ.
+#
 
 . /lib/svc/share/smf_include.sh
 . /lib/svc/share/fs_include.sh
@@ -36,13 +40,7 @@ if [  `uname -p` = "sparc" ]; then
 	exit $SMF_EXIT_OK
 fi
 
-#
-# Check the boot archive content against root filesystem.
-# Return failure if they differ.
-#
-if [ "${_INIT_ZONENAME:=`/sbin/zonename`}" != "global" ]; then
-	exit $SMF_EXIT_OK
-fi
+smf_is_globalzone || exit $SMF_EXIT_OK
 
 #
 # Make sure we return failure only once. If user choose to ignore
